# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"
  apt_packages:
    - imagemagick
  jobs:
    pre_install:
      - which convert
      - bash ./scripts/pre_install.sh

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
